name: Create Draft Release

permissions:
    contents: write

on:
    push:
        tags:
            - "v*"

jobs:
    build-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout sources
              uses: actions/checkout@v4

            - name: Create zip archive
              run: |
                  mkdir build
                  zip -r build/3D-Default-Compat.zip assets pack.mcmeta pack.png

            - name: Create draft release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref_name }}
                  release_name: 3D Default Compat ${{ github.ref_name }}
                  draft: true
                  prerelease: false
                  body: "-"

            - name: Upload ZIP to the release
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: build/3D-Default-Compat.zip
                  asset_name: 3D-Default-Compat.zip
                  asset_content_type: application/zip
